version: "3.0"
services:
  seatable:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "seatable"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      API_TOKEN: key1234567890
      TABLE: myTable
    ports:
      - 80:80
